-- Usuário
CREATE TABLE "User"(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL,
	type int NOT NULL,
	phone_number varchar(20) NOT NULL,
	email varchar(160) NOT NULL,
	password varchar(60) NOT NULL
);


-- Local

CREATE TABLE "PlanningUnit" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL
);

CREATE TABLE "PlanningRegion" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL,
	planning_unit_id int REFERENCES "PlanningUnit"
);

CREATE TABLE "Address" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep varchar(10) NOT NULL,
    UF varchar(100) NOT NULL,
    city varchar(100) NOT NULL,
    neighborhood varchar(100) NOT NULL,
    street varchar(255) NOT NULL,
    number int NOT NULL,
    complement varchar(255),
	planning_region_id int REFERENCES "PlanningRegion"
);

CREATE TABLE "Local" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL,
    nickname varchar(255) NOT NULL,
	type int NOT NULL,
	free_space_category int,
    comments TEXT,
    creation_year varchar(4),
    reform_year varchar(4),
    mayor_creation varchar(255),
    legislation varchar(255),
    useful_area NUMERIC(7,2),
	area_pjf NUMERIC(7,2),
    angle_inclination NUMERIC(7,2),
    urban_region BOOLEAN,
    inactive_not_found BOOLEAN NOT NULL,
	address_id int REFERENCES "Address"
);

CREATE TABLE "Event" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description varchar(255) NOT NULL,
	local_id int REFERENCES "Local"
);


-- Contagem
CREATE TABLE "PersonOnLocal" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	age_rating int NOT NULL,
	physical_activity BOOLEAN NOT NULL,
	deficiency_person BOOLEAN NOT NULL,
	illegal_activity BOOLEAN NOT NULL,
	homeless BOOLEAN NOT NULL
);

CREATE TABLE "Counting" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL,
	init_date_time timestamp NOT NULL,
	end_date_time timestamp NOT NULL,
	count_animals int DEFAULT 0,
	temperature NUMERIC(7,2),
	sky varchar(50),
    person_on_local_id int REFERENCES "PersonOnLocal",
	local_id int REFERENCES "Local"
);


-- Avaliação
CREATE TABLE "Evaluation" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL,
	type NUMERIC(7,2) NOT NULL,
	email NUMERIC(7,2),
	password varchar(60) NOT NULL,
	user_id int REFERENCES "User"
);

CREATE TABLE "Noise" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	db_level NUMERIC(7,2) NOT NULL,
	is_weekend BOOLEAN NOT NULL,
	positioning int NOT NULL,
	category int NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "Morphology" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	category int NOT NULL,
	divided BOOLEAN NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "Via" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	typology varchar(100) NOT NULL,
	morphology_id int REFERENCES "Morphology"
);

CREATE TABLE "UseDensityAround" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	use_type NUMERIC(7,2) NOT NULL,
	institutional_use BOOLEAN NOT NULL,
	count_houses int NOT NULL,
	others_relevant_elements varchar(255) NOT NULL,
	night_use BOOLEAN NOT NULL,
	day_use BOOLEAN NOT NULL,
	third_place BOOLEAN NOT NULL,
	third_place_description TEXT NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "StreetSafety" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	crosswalk BOOLEAN NOT NULL,
	semaphore BOOLEAN NOT NULL,
	protection_fence BOOLEAN NOT NULL,
	speed_limit_plate BOOLEAN NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "PeoplePositioning" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "Photo" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description varchar(255) NOT NULL,
	path TEXT NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "Suveirllance" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	camera BOOLEAN NOT NULL,
	police_station BOOLEAN NOT NULL,
	visibility INT NOT NULL,
	permeable_facade INT NOT NULL,
	active_facade INT NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "Depredation" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	graffiti INT NOT NULL,
	abandonment INT NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "AcessAround" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name_plate INT NOT NULL,
	trasport_point INT NOT NULL,
	taxi_point INT NOT NULL,
	fence BOOLEAN NOT NULL,
	vihicle_parking INT NOT NULL,
	motorcycle_parking INT NOT NULL,
	bike_lane BOOLEAN NOT NULL,
	bike_rack INT NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "Accessibility" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	seidewalk INT NOT NULL,
	type INT NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "Playground" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL,
	material_type INT NOT NULL,
	quantity INT NOT NULL,
	crack_greater_8mm BOOLEAN NOT NULL,
	pointed_object BOOLEAN NOT NULL,
	sharp_corner BOOLEAN NOT NULL,
	conservation INT NOT NULL,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "UseAreaEvaluation" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	quantity INT NOT NULL,
	shadow_area BOOLEAN NOT NULL,
	lighting BOOLEAN NOT NULL,
	walled BOOLEAN NOT NULL,
	seats BOOLEAN NOT NULL,
	conservation INT NOT NULL,
	meter INT NOT NULL,
	photo_path TEXT,
	evaluation_id int REFERENCES "Evaluation"
);

CREATE TABLE "UseArea" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	element varchar(255) NOT NULL,
	type INT NOT NULL,
	use_area_eval_id int REFERENCES "UseAreaEvaluation"
);