import { josefin_sans } from "@/lib/fonts";
import type { Metadata } from "next";
import { ReactNode } from "react";

import "./globals.css";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={josefin_sans.className}>{children}</body>
    </html>
  );
};

export { metadata };
export default RootLayout;
