import { shanti } from "@/lib/fonts";
import type { Metadata, Viewport } from "next";
import { ReactNode } from "react";

import { LoadingOverlayProvider } from "../components/context/loadingContext";
import "./globals.css";

const metadata: Metadata = {
  title: "Praças",
  description: "Generated by create next app",
};

const viewport: Viewport = {
  themeColor: "#608E66",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${shanti.className}`}>
        <LoadingOverlayProvider>{children}</LoadingOverlayProvider>
      </body>
    </html>
  );
};

export { metadata, viewport };
export default RootLayout;
